### ISSUE TITLE
eof

### ISSUE THREAD

**Issue by Zumbalamambo** [blacksteed232/trafficMonitorPrototype#4]
It is throwing EOF error. Why so?

**Comment by akphi** [comment]
@Zumbalamambo can you give me the detail of what you did and the output? Please do not open an issue like this without giving any context, such as the version of Python you are using. Also, have you change the file input? Apparently, it was working for many other people, that's why I wonder if it has something to do with your own setup. I will leave this open for now, but will close within a few days.
