### ISSUE TITLE
Hello, I want to use my code to achieve pedestrian detection, and use your code to track and count. Is that ok? How should I change the code

### ISSUE THREAD

**Issue by ss199302** [blacksteed232/trafficMonitorPrototype#9]
Hello, I want to use my code to achieve pedestrian detection, and use your code to track and count. Is that ok? How should I change the code？

**Comment by yaaasssss** [comment]
I want to do the same ,is there anyone who can help.
I have my code of detection and just want to add the code to track and count and put a time in and time out tag !.

**Comment by akphi** [comment]
@ss199302 @yaaasssss Sorry I was carried away with other works and have no time to answer this. But welcome to use my code to track and count. As for how to use it, I was not really good at separating my code at the point in time, so I cannot really tell you to use which part of the code to do exactly track and count. But the general idea is after detecting movement using Meanshift/Camshift (line 311 and beyond), I try to see which person is which, by assuming that the rectangular frame contouring that person shouldn't move too much. So I will say focus on that portion of the code. 

The key idea behind tracking is that we can use OpenCV to detect motion and show blob/area where movements have occurred, but we have to do the interpretation. In other words, we have to tell it, this blob from frame (n)th represents the same object as does that blob in frame (n+1)th. Oh, so in that case, we consider that blob moves. Otherwise, if the blob has no nearby blob in the next frame, the blob is gone or it simply stops the motion (think about the case when somebody just stops moving). Also, we have to account for new people coming (I thought I have commented that quite clearly in my code).

There are also many other considerations such as, how do you consider a blob a person. Well of course if you can use some advanced recognition algorithm then go ahead, but for my case, I use a simple trick to assume that humans are on average this size, and I have a threshold for that so that a bird or a dog cannot be mistaken for a person (But of course in some case, this can happen if you have a giant dog, or a bird flying close to the camera).

The problem with tracking is all about making assumptions based on what you know of the object you are going to track as well as the setting of the cameras.

Happy tracking!!!
